# Example GitHub Actions Workflow using AWS OIDC
# Save this as .github/workflows/deploy-aws.yml in your repository

name: Deploy to AWS with OIDC

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Required for OIDC authentication
permissions:
  id-token: write   # Required for requesting JWT token
  contents: read    # Required for checking out code

jobs:
  # Job 1: Plan (read-only)
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (Read-Only Role)
        uses: aws-actions/configure-aws-credentials@v4
        # Replace 'YOUR_ACCOUNT_ID' below with your actual AWS account ID, or use the Terraform output that provides this value.
        with:
          role-to-assume: arn:aws:iam::YOUR_ACCOUNT_ID:role/github-actions-readonly
          aws-region: eu-north-1
          role-session-name: GitHubActions-Plan

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity
          echo "Successfully authenticated with AWS using OIDC!"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/tfplan
          retention-days: 5

  # Job 2: Apply (deploy role, only on main branch)
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: production
      url: https://console.aws.amazon.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (Deploy Role)
        uses: aws-actions/configure-aws-credentials@v4
        # Replace 'YOUR_ACCOUNT_ID' below with your actual AWS account ID, or use the Terraform output that provides this value.
        with:
          role-to-assume: arn:aws:iam::YOUR_ACCOUNT_ID:role/github-actions-deploy
          aws-region: eu-north-1
          role-session-name: GitHubActions-Deploy
          role-duration-seconds: 3600  # 1 hour

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity
          echo "Deploying with role: $(aws sts get-caller-identity --query Arn --output text)"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

  # Job 3: AWS CLI Examples
  aws-operations:
    name: AWS CLI Operations
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::YOUR_ACCOUNT_ID:role/github-actions-deploy
          aws-region: eu-north-1

      - name: List S3 Buckets
        run: aws s3 ls

      - name: List EC2 Instances
        run: aws ec2 describe-instances --query 'Reservations[*].Instances[*].[InstanceId,State.Name,Tags[?Key==`Name`].Value|[0]]' --output table

      - name: Check CloudWatch Logs
        run: aws logs describe-log-groups --limit 10

  # Job 4: Multi-region deployment
  deploy-multi-region:
    name: Deploy to Multiple Regions
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        region: [eu-north-1, us-east-1, ap-southeast-1]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        # Replace 'YOUR_ACCOUNT_ID' below with your actual AWS account ID, or use the Terraform output that provides this value.
        with:
          role-to-assume: arn:aws:iam::YOUR_ACCOUNT_ID:role/github-actions-deploy
          aws-region: ${{ matrix.region }}

      - name: Deploy to ${{ matrix.region }}
        run: |
          echo "Deploying to ${{ matrix.region }}"
          aws sts get-caller-identity
          # Add your deployment commands here
